modLoader = "javafml"
license = "LGPL 2.1"
issueTrackerURL = "https://github.com/Darkhax-Minecraft/Distracting-Trims/issues"

[[mods]]
modId = "distractingtrims"
version = "26.1.2.0"
displayName = "DistractingTrims"
updateJSONURL = "https://updates.blamejared.com/get?n=distractingtrims&gv=26.1.2&ml=neoforge"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/distracting-trims"
logoFile = "logo_distractingtrims.png"
logoBlur = false
credits = "This project is made possible with Patreon support from players like you. Thank you! lothrazar, techsquirrel, Keyana , Darkosto, Tobias Ward, noobanidus"
authors = "Darkhax"
description = "Golden armor trims distract piglins from attacking you."

[[mixins]]
config = "distractingtrims.common.mixins.json"

[[mixins]]
config = "distractingtrims.neoforge.mixins.json"

[[dependencies.distractingtrims]]
modId = "minecraft"
type = "required"
versionRange = "26.1"
ordering = "NONE"
side = "BOTH"

[[dependencies.distractingtrims]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.0.1-beta,)"
ordering = "NONE"
side = "BOTH"

